spring:
  application:
    name: "filestore"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/filestore
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

file:
  upload-dir: ./

server:
  port: 8088
